[package]
name = "ethereum-fluid"
version = "0.1.0"
edition = "2021"

[lib]
name = "ethereum_fluid"
crate-type = ["cdylib"]

[dependencies]
substreams.workspace = true
substreams-ethereum.workspace = true
prost.workspace = true
tycho-substreams.workspace = true